baseURL = "https://dotnet-cookbook.dmitriydubson.com"
languageCode = "en-us"
theme = "hugo-theme-learn"
title = ".NET Core Cookbook"

[params]
themeVariant = "blue"
disableInlineCopyToClipBoard = true

[outputs]
home = [ "HTML", "RSS", "JSON"]
